from pathlib import Path

path = Path("src/mastra/tools/vocabularyTools.ts")
text = path.read_text(encoding="utf-8")

old_quick = "        logger?.info('?Y\"? [AddCard] Creating card with parsed data:', cardData);\r\n        const card = await createCard(cardData);\r\n\r\n        logger?.info('?o. [AddCard] Card created successfully:', { id: card.id, front: card.front, back: card.back });\r\n        return {\r\n          success: true,\r\n          card_id: card.id,\r\n          message: `Card created successfully! ${card.front} ??' ${card.back}${card.tags.length > 0 ? ` [${card.tags.join(', ')}]` : ''}`,\r\n          card: {\r\n            id: card.id,\r\n            front: card.front,\r\n            back: card.back,\r\n            tags: card.tags,\r\n            example: card.example,\r\n            lang_front: card.lang_front,\r\n            lang_back: card.lang_back,\r\n          }\r\n        };"

new_quick = "        logger?.info(\"[AddCard] Creating card with parsed data:\", cardData);\n        try {\n          const card = await createCard(cardData);\n\n          logger?.info(\"[AddCard] Card created successfully:\", { id: card.id, front: card.front, back: card.back });\n          return {\n            success: true,\n            card_id: card.id,\n            message: `Card created successfully! ${card.front} -> ${card.back}${card.tags.length > 0 ? ` [${card.tags.join(\", ")}]` : \"\"}`,\n            card: {\n              id: card.id,\n              front: card.front,\n              back: card.back,\n              tags: card.tags,\n              example: card.example,\n              lang_front: card.lang_front,\n              lang_back: card.lang_back,\n            },\n          };\n        } catch (error) {\n          if (error instanceof DuplicateCardError) {\n            logger?.info(\"[AddCard] Duplicate detected in quick-add:\", { ownerId: context.owner_id, front });\n            return await buildDuplicateResponse(context.owner_id, front, error);\n          }\n          throw error;\n        }"

text = text.replace(old_quick, new_quick)

old_guided = "      logger?.info('?Y\"? [AddCard] Creating card with guided data:', cardData);\r\n      const card = await createCard(cardData);\r\n\r\n      logger?.info('?o. [AddCard] Card created successfully:', { id: card.id, front: card.front, back: card.back });\r\n      return {\r\n        success: true,\r\n        card_id: card.id,\r\n        message: `Card created successfully! ${card.front} ??' ${card.back}${card.tags.length > 0 ? ` [${card.tags.join(', ')}]` : ''}`,\r\n        card: {\r\n          id: card.id,\r\n          front: card.front,\r\n          back: card.back,\r\n          tags: card.tags,\r\n          example: card.example,\r\n          lang_front: card.lang_front,\r\n          lang_back: card.lang_back,\r\n        }\r\n      };\r\n\r\n"

new_guided = "      logger?.info(\"[AddCard] Creating card with guided data:\", cardData);\n\n      try {\n        const card = await createCard(cardData);\n\n        logger?.info(\"[AddCard] Card created successfully:\", { id: card.id, front: card.front, back: card.back });\n        return {\n          success: true,\n          card_id: card.id,\n          message: `Card created successfully! ${card.front} -> ${card.back}${card.tags.length > 0 ? ` [${card.tags.join(\", ")}]` : \"\"}`,\n          card: {\n            id: card.id,\n            front: card.front,\n            back: card.back,\n            tags: card.tags,\n            example: card.example,\n            lang_front: card.lang_front,\n            lang_back: card.lang_back,\n          },\n        };\n      } catch (error) {\n        if (error instanceof DuplicateCardError) {\n          logger?.info(\"[AddCard] Duplicate detected in guided flow:\", { ownerId: context.owner_id, front: context.front });\n          return await buildDuplicateResponse(context.owner_id, context.front, error);\n        }\n        throw error;\n      }\n\n"

text = text.replace(old_guided, new_guided)

path.write_text(text, encoding="utf-8")
